name: Mirror to Friend's Repository

on:
  push:
    branches: ['**']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Custom Identity
      run: |
        # Use a custom identity instead of github-actions[bot]
        git config user.name "Mirror Bot"
        git config user.email "mirror-bot@example.com"

    - name: Push to Friend's Repo
      env:
        TOKEN: ${{ secrets.FORK_TOKEN }}
      run: |
        # Push directly using token in URL (bypasses default auth)
        git push https://x-access-token:$TOKEN@github.com/yubiStona/RPS-UI-forked.git --all --force
