name: Mirror to Friend's Repository

on:
  push:
    branches: [main, master, develop]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Configure Git
      run: |
        git config user.name "CI/CD Mirror Bot"
        git config user.email "ci-cd-bot@users.noreply.github.com"

    - name: Mirror to Friend's Repository
      run: |
        git remote add friend git@github.com:yubiStona/RPS-UI-forked.git
        git push friend main --force
        git push friend --tags --force
