name: Mirror to Friend's Repository

on:
  push:
    branches: [ main, master, develop ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Mirror to Friend's Repository
      env:
        TOKEN: ${{ secrets.FORK_TOKEN }}
      run: |
        # Use the token directly in the push URL (this is the key fix!)
        git push https://yubiStona:$TOKEN@github.com/yubiStona/RPS-UI-forked.git main --force --verbose
        
        # Alternative: Push current branch
        # BRANCH_NAME=${GITHUB_REF#refs/heads/}
        # git push https://yubiStona:$TOKEN@github.com/yubiStona/RPS-UI-forked.git $BRANCH_NAME --force
