name: Mirror to Friend's Repository

on:
  push:
    branches: [ main, master, develop ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Archive and Push via API
      env:
        TOKEN: ${{ secrets.FORK_TOKEN }}
      run: |
        # Create a zip archive of the current code
        zip -r repo-content.zip . -x ".git/*" ".github/*"
        
        # Get the current branch name
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        
        # Upload to friend's repository using GitHub API
        echo "Uploading to yubiStona/RPS-UI-forked on branch $BRANCH_NAME"
        
        # Use GitHub API to create a commit
        curl -X POST \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -F "message=Automated mirror from GitHub Actions" \
          -F "content=@repo-content.zip" \
          -F "branch=$BRANCH_NAME" \
          "https://api.github.com/repos/yubiStona/RPS-UI-forked/contents?path=."
