name: Debug Mirror Issue

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Repository Access
      run: |
        # Test if we can access the target repo
        echo "Testing access to friend's repository..."
        response=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Authorization: token ${{ secrets.FORK_TOKEN }}" \
          https://api.github.com/repos/yubiStona/RPS-UI-forked)
        
        echo "HTTP Response Code: $response"
        
        if [ "$response" -eq 200 ]; then
          echo "✅ Success: Can access repository"
        else
          echo "❌ Error: Cannot access repository (HTTP $response)"
          exit 1
        fi

    - name: Configure Git and Test Push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Add remote
        git remote add friend https://yubiStona:${{ secrets.FORK_TOKEN }}@github.com/yubiStona/RPS-UI-forked.git
        
        # Test push with detailed output
        echo "Attempting push..."
        git push friend main --force --verbose 2>&1 | tee push_output.log
        
        # Check exit code
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
          echo "✅ Push successful!"
        else
          echo "❌ Push failed!"
          cat push_output.log
          exit 1
        fi
