name: Mirror to Friend's Repository

on:
  push:
    branches: [ main, master, develop ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Mirror to Friend's Repository
      run: |
        # Use this format - token only, no username
        git remote add friend https://${{ secrets.FORK_TOKEN }}@github.com/yubiStona/RPS-UI-forked.git
        
        # Get current branch name
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "Pushing branch: $BRANCH_NAME"
        
        # Push with verbose output
        git push friend $BRANCH_NAME --force --verbose
