name: Mirror to Friend's Repository

on:
  push:
    branches: ['**']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Force Git to Use Token with Credential Store
      env:
        TOKEN: ${{ secrets.FORK_TOKEN }}
      run: |
        # Configure git identity
        git config user.name "Mirror Bot"
        git config user.email "mirror-bot@example.com"
        
        # FORCE Git to use our token by setting up credential store
        echo "https://x-access-token:$TOKEN@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials
        git config --global credential.helper 'store --file=/home/runner/.git-credentials'
        
        # Now push - Git will be forced to use our credentials
        git push https://github.com/yubiStona/RPS-UI-forked.git --all --force --verbose
